lesson_12_chapter_4 status: commit
cosmos-developer/baby pull request #26
Opened 2023-03-16 13:30 UTC by kaito2001

2023-03-16 17:50 UTC, nghuyenthevinh2000 requested changes

2023-03-16 17:50 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +
Learners should be able to add new account to auth, add initial balances to bank

2023-03-16 17:50 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +app.go: Is the place where all modules for blockchain operation are aggregated.
no need to mention app.go here since scope is genesis only

2023-03-16 17:50 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +## Guidelines
Wrong explaination for all 3 module since the scope is genesis only. Should only care about simple explaination of 3 mods.

2023-03-16 17:50 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +3. Create, edit validator with module staking successfully
Need a homework that check if people have added new account and added initial balances to bank

2023-03-17 10:18 UTC, kaito2001 commented
@nghuyenthevinh2000  check hộ em nhé

2023-03-17 11:30 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +bash scripts/test-node-deploy.sh --install
Add flag --initialize as well

2023-03-21 02:54 UTC, nghuyenthevinh2000 requested changes

2023-03-21 02:54 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +In this lesson, I will continue to introduce more important fields in the genesis.json file (auth, bank, staking).
```suggestion
In this lesson, I will talk about three fields in app_state (auth, bank, staking) in genesis.json.
```

2023-03-21 02:54 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +In this lesson, I will continue to introduce more important fields in the genesis.json file (auth, bank, staking).
@kaito2001 em nhớ ghi thêm giải thích ngắn gọn cho app_state là gì trong genesis.json

2023-03-21 02:54 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +
Chuyển giải thích về auth, bank, staking lên trước ##Guidelines. 

Không ghi kiến thức trong Guidelines

Đọc lại format lesson: https://github.com/cosmos-developer/baby/blob/main/docs/lesson_format.md

2023-03-21 02:54 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +* auth: in this field, we will take care of each field account
chuyển lên trước guidelines

2023-03-21 02:54 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +* base_account: defines a base account type. It contains all the necessary fields for basic account functionality. Any custom account type should extend this type for additional functionality (e.g. v
chuyển lên trước guidelines

2023-03-21 02:54 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +4. The bank module : there are two most important in this module, which are transaction execution and account balance.
chuyển lên trước guidelines

2023-03-21 02:54 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_12.md
> +
@kaito2001 ảnh của genesis.json cho thấy account và bank được tạo

2023-03-22 04:49 UTC, kaito2001 commented
@nghuyenthevinh2000  [c547191](https://github.com/cosmos-developer/baby/pull/26/commits/c5471915608ae9c34b3256443f0cdd9a546056fe)

2023-03-24 13:58 UTC, nghuyenthevinh2000 approved these changes

2023-03-24 13:58 UTC, merged