Lesson_13_chapter_4
cosmos-developer/baby pull request #28
Opened 2023-03-24 14:04 UTC by kaito2001

2023-03-26 14:35 UTC, kaito2001 commented
@nghuyenthevinh2000  [144babe](https://github.com/cosmos-developer/baby/pull/28/commits/144babe37e10e45965d3619fe62080a1c860aca2)

2023-03-28 04:22 UTC, nghuyenthevinh2000 requested changes

2023-03-28 04:22 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_13.md
> +## Guidelines
guideline phải thay đổi 3 trường, có ảnh showcase

2023-03-30 18:12 UTC, nghuyenthevinh2000 requested changes

2023-03-30 18:12 UTC, nghuyenthevinh2000 commented on scripts/test-node-deploy.sh
> +# check if CHAINID is not defined
change to, it will do the same. This one will assign baby-1 if CHAINID is not set

```bash
CHAINID="${CHAINID:-baby-1}"
```

2023-03-30 18:12 UTC, nghuyenthevinh2000 commented on scripts/test-node-deploy.sh
> +cat $HOME/.baby/config/genesis.json | jq '.app_state["mint"]["params"]["mint_denom"]="udaddy"' > $HOME/.baby/config/tmp_genesis.json && mv $HOME/.baby/config/tmp_genesis.json $HOME/.baby/config/genes
do not change "ubaby" to "udaddy" in this script.

Take a picture and show how student can change "ubaby" to "udaddy" instead

2023-03-30 18:13 UTC, nghuyenthevinh2000 requested changes

2023-03-30 18:13 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_13.md
> +In this 'mint' field:
```suggestion
1. In this 'mint' field:
```

2023-03-30 18:13 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_13.md
> +In this 'distribution' field:
```suggestion
2. In this 'distribution' field:
```

2023-03-30 18:13 UTC, nghuyenthevinh2000 commented on docs/chapter_4/lesson_13.md
> +In this 'gov' field:
```suggestion
3. In this 'gov' field:
```

2023-03-31 05:26 UTC, nghuyenthevinh2000 approved these changes

2023-03-31 05:26 UTC, merged